sudo: false
language: node_js
node_js:
  - stable
notifications:
  email: false
install:
  - npm install
services:
  - postgresql
  - redis-server
before_script:
  - psql -c 'create database barefoot_test;' -U postgres
script:
  - npm test
after_success:
  - npm run coverage
